name: Get Unverified
on:
  workflow_dispatch
jobs:
  getUnverified:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
         with:
          fetch-depth: 0
       - run: |
          shopt -s globstar extglob
          python3 checks/get_unverified.py docs/**/*.md > unverified.txt
          cat unverified.txt
          total="$(echo docs/**/*.md | wc -w)"
          unverified="$(cat unverified.txt | wc -l)"
          percent="$(echo "(100-(100*$unverified/$total))" | bc)"
          verified=$((total - unverified))
          printf "%s / %s verified. ( %s%% )\n" $verified $total $percent
