name: Lint Changed Files
on:
  push:
    branches:
      - main
    paths:
      - docs/*.md
jobs:
  proselint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install proselint
      - run: proselint "$(git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA **/*.md)"
  mdlint:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - run: npm install markdownlint --save-dev
       - run: markdownlint "$(git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA **/*.md"
  dirty:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - run: pip install -r requirements.txt
       - run: mkdocs gh-deploy -b gh-pages-test --force --dirty --verbose 
